; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; Just realized that the test and megaatmega2560 environments are identical,
; so we can just have one environment and use test flags to differentiate between them.
; This way we avoid code duplication and keep the configuration cleaner.
[env]
platform = atmelavr
board = megaatmega2560
framework = arduino

[env:megaatmega2560]
; Inherit from the default environment

[env:test]
; Inherit from the default environment


; [env:test_windows]
; platform = native
; ;framework = native
; lib_deps = throwtheswitch/Unity@^2.5.2
; build_flags = -D WINDOWS_TEST=1
; ;build_flags = -DTEST_PLATFORM_WINDOWS
; test_filter = test_util_win*
