#set up c# sdk (opt: and rabbitMQ, shouldn't be needed)
#build grpc_server
#maybe install gcc to set up PIO
#set up PIO
#build sensor_client_c
#build sensors
#run tests for each
#run grpc_server
#run sensor_client_c
name: IoT Workflow

on:
  push:
    branches: [ develop ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: build and test gRPC server
      run: |
        dotnet build services/iot-service/Grpc-Server/Grpc-Server.csproj
        dotnet test services/iot-service/Grpc_Test/Grpc_Test.csproj
    - name: Install build tools and RabbitMQ
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake librabbitmq-dev rabbitmq-server
    - name: Build Sensor Client C (CMake)
      run: |
        cd internet_of_things/sensor_client_c
        mkdir build
        cd build
        # On Linux, apt-get puts rabbitmq in standard paths, so CMake finds it automatically
        cmake ..
        make
    - name: Run C Unit Tests (Unity)
      run: |
        cd internet_of_things/sensor_client_c/build
        ./test_message_builder
        ./test_sensor_reader    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Build Arduino Sensors (PlatformIO)
      run: |
        cd internet_of_things/Sensors
        pio run

#CI forkflow to be added at the end of the project, when we have more code to test and build